[versions]
agp = "8.10.1"
kotlin = "2.1.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2025.09.00"
hilt = "2.56.2"
kotlinx-coroutines-core = "1.8.0"
materialVersion = "1.3.1"
constraintlayoutCompose = "1.0.1"
hiltNavigationCompose = "1.1.0"
navigationCompose = "2.7.6"
okhttp = "4.10.0"
gson = "2.9.0"
jetbrainsKotlinJvm = "2.0.21"
appcompat = "1.7.1"
material = "1.10.0"
ksp = "2.1.0-1.0.29"
roomCompiler = "2.7.2"
roomKtx = "2.7.2"
roomRuntime = "2.7.2"
solanakt = "1.1.5"
coil = "3.3.0"
mozart = "0.1.2"
exoplayer = "2.18.2"
filamentAndroid = "1.69.1"
ui = "1.3.3"

[libraries]
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialVersion" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
solanakt = { module = "com.github.metaplex-foundation:SolanaKT", version.ref = "solanakt" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }

filament-android = { module = "com.google.android.filament:filament-android", version.ref = "filamentAndroid" }
gltfio-android = { module = "com.google.android.filament:gltfio-android", version.ref = "filamentAndroid" }
filament-utils-android = { module = "com.google.android.filament:filament-utils-android", version.ref = "filamentAndroid" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }

mozart = { module = "io.github.creativedrewy:mozartwallpapers", version.ref = "mozart" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

